title: Exotic Server
description: Servidor Minecraft Exotic — tutoriais, comandos e mapa ao vivo
baseurl: "/mc-exotic-server"
url: "https://exotic-group.github.io"

markdown: kramdown

sass:
  style: compressed
