title: Exotic Server
description: Minecraft Exotic Server — tutorials, commands, and live map
baseurl: "/mc-exotic-server"
url: "https://exotic-group.github.io"

markdown: kramdown

sass:
  style: compressed
